# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: FirstJob
  timeoutInMinutes: 10
  steps:
    - bash: echo "This is first job"

- job: SecondJob
  steps:
    - bash: echo "This is second Job"